# -*- coding: utf-8 -*-
"""PRODIGY_TASK_1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1av5QzP3ibR-rN5wJs9IqUTcuOE5Bhb6P
"""



from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,r2_score
import warnings
warnings.filterwarnings('ignore')
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

data=pd.read_csv('/content/Housing.csv')

data.head()

data.isnull().sum()

data.isna().sum()

data.describe()

import pandas as pd

new_data_train = pd.DataFrame()

new_data_train = pd.concat([data["Avg. Area Income"],data["Avg. Area House Age"],data["Avg. Area Number of Rooms"],data["Avg. Area Number of Bedrooms"],data["Price"]],axis=1)

from sklearn.decomposition import PCA

PCA_columns = ['Avg. Area Income', 'Avg. Area House Age', 'Avg. Area Number of Rooms']

pca = PCA(n_components=2)

dimen_reduced_columns = pca.fit_transform(data[PCA_columns])

data_pca_train = pd. DataFrame (dimen_reduced_columns)

new_data_train = pd.concat([data_pca_train,new_data_train], axis=1)
new_data_train.rename({'0': 'PCA_1', '1': 'PCA_2'}, inplace=True)

new_data_train.columns = new_data_train.columns.astype(str)

new_data_train.head()

Xtrain=new_data_train.drop(["Price"],axis=1)
Ytrain=new_data_train["Price"]
X_train,X_test,Y_train,Y_test=train_test_split(Xtrain,Ytrain,test_size=0.2,random_state=123)

dataplot = sns.heatmap(new_data_train.corr())

model=LinearRegression()
model.fit(X_train,Y_train)

pred=model.predict(X_test)

mse=mean_squared_error(pred,Y_test)

print(mse)

r2=r2_score(pred,Y_test)
r2