# -*- coding: utf-8 -*-
"""PRODIOGY_TASK_2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ho55J-LO3LyPzQMdyea5FgTJYzrNusur
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
# %matplotlib inline

from google.colab import files
uploaded=files.upload()

import io

df=pd.read_csv(io.BytesIO(uploaded['Mall_Customers (1).csv']))
df.shape

df.head()

df["A"]=df[["Annual Income (k$)"]]
df["B"]=df[["Spending Score (1-100)"]]

x=df[["A","B"]]
x.head()

plt.scatter(x["A"],x["B"],s=15,c="r")
plt.show()

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
# %matplotlib inline

kmean=KMeans(n_clusters=5)
kmean.fit(x)

centers=kmean.cluster_centers_
print(kmean.cluster_centers_)

clusters=kmean.fit_predict(x)
df["label"]=clusters
df.head(100)

col=['green','blue','black','red','purple']

for i in range(5):
  a=col[i]
  #print(a)
  plt.scatter(df.A[df.label==i],df.B[df.label==i],c=a,label='cluster 1')
plt.scatter(centers[:,0],centers[:,1],marker='*',s=300,c='r',label='centroid')

x1=x.loc[:,["A","B"]].values

WCSS=[]
for k in range(1,11):
  kmeans=KMeans(n_clusters=k,init="k-means++")
  kmeans.fit(x1)
  WCSS.append(kmeans.inertia_)
plt.figure(figsize=(12,6))
plt.grid()
plt.plot(range(1,11),WCSS,linewidth=2,color="blue",marker="8")
plt.xlabel("K value")
plt.ylabel("WCSS")
plt.show()